version: '3.8'
services:
  db:
    image: postgres:15
    container_name: rupio_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: rupio_db
    ports:
      - "5432:5432"
    volumes:
      - rupio_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: rupio_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@rupio.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  rupio_data:

